
public class Numbers {
	public static void main(String[] args) {
		long i0 = 2147483648L;
		long i1 = 9999999999L;
		long i2 = 5999999999L;
		long i3 = 3999999999L;
		long i4 = 1999999999L;
		long i5 = -i1;
		long i6 = -i2;
		long i7 = -i3;
		long i8 = -i4;
		long i9 = Long.MIN_VALUE;
		long i10 = 0L;
		System.out.println(Long.toBinaryString(i0));
		System.out.println(Long.toBinaryString(i1));
		System.out.println(Long.toBinaryString(i2));
		System.out.println(Long.toBinaryString(i3));
		System.out.println(Long.toBinaryString(i4));
		System.out.println(Long.toBinaryString(i5));
		System.out.println(Long.toBinaryString(i6));
		System.out.println(Long.toBinaryString(i7));
		System.out.println(Long.toBinaryString(i8));
		System.out.println(Long.toBinaryString(i9));
		System.out.println(Long.toBinaryString(i10));
		System.out.println("*");
		System.out.println((int) i0);
		System.out.println((int) i1);
		System.out.println((int) i2);
		System.out.println((int) i3);
		System.out.println((int) i4);
		System.out.println((int) i5);
		System.out.println((int) i6);
		System.out.println((int) i7);
		System.out.println((int) i8);
		System.out.println((int) i9);
		System.out.println((int) i10);
		System.out.println("**");
		System.out.println((int) (i0 >> 32));
		System.out.println((int) (i1 >> 32));
		System.out.println((int) (i2 >> 32));
		System.out.println((int) (i3 >> 32));
		System.out.println((int) (i4 >> 32));
		System.out.println((int) (i5 >> 32));
		System.out.println((int) (i6 >> 32));
		System.out.println((int) (i7 >> 32));
		System.out.println((int) (i8 >> 32));
		System.out.println((int) (i9 >> 32));
		System.out.println((int) (i10 >> 32));
		System.out.println("***");
		System.out.println((int) (i0 >> 32L));
		System.out.println((int) (i1 >> 32L));
		System.out.println((int) (i2 >> 32L));
		System.out.println((int) (i3 >> 32L));
		System.out.println((int) (i4 >> 32L));
		System.out.println((int) (i5 >> 32L));
		System.out.println((int) (i6 >> 32L));
		System.out.println((int) (i7 >> 32L));
		System.out.println((int) (i8 >> 32L));
		System.out.println((int) (i9 >> 32L));
		System.out.println((int) (i10 >> 32L));
		System.out.println("****");
		System.out.println((int) (i0 >>> 32));
		System.out.println((int) (i1 >>> 32));
		System.out.println((int) (i2 >>> 32));
		System.out.println((int) (i3 >>> 32));
		System.out.println((int) (i4 >>> 32));
		System.out.println((int) (i5 >>> 32));
		System.out.println((int) (i6 >>> 32));
		System.out.println((int) (i7 >>> 32));
		System.out.println((int) (i8 >>> 32));
		System.out.println((int) (i9 >>> 32));
		System.out.println((int) (i10 >>> 32));
		System.out.println("*****");
		System.out.println((int) ((i0 >> 63) | (-i0 >>> 63)));
		System.out.println((int) ((i1 >> 63) | (-i1 >>> 63)));
		System.out.println((int) ((i2 >> 63) | (-i2 >>> 63)));
		System.out.println((int) ((i3 >> 63) | (-i3 >>> 63)));
		System.out.println((int) ((i4 >> 63) | (-i4 >>> 63)));
		System.out.println((int) ((i5 >> 63) | (-i5 >>> 63)));
		System.out.println((int) ((i6 >> 63) | (-i6 >>> 63)));
		System.out.println((int) ((i7 >> 63) | (-i7 >>> 63)));
		System.out.println((int) ((i8 >> 63) | (-i8 >>> 63)));
		System.out.println((int) ((i9 >> 63) | (-i9 >>> 63)));
		System.out.println((int) ((i10 >> 63) | (-i10 >>> 63)));
		System.out.println("******");
		System.out.println((int) ((i0 >> 62) | (-i0 >>> 62)));
		System.out.println((int) ((i1 >> 62) | (-i1 >>> 62)));
		System.out.println((int) ((i2 >> 62) | (-i2 >>> 62)));
		System.out.println((int) ((i3 >> 62) | (-i3 >>> 62)));
		System.out.println((int) ((i4 >> 62) | (-i4 >>> 62)));
		System.out.println((int) ((i5 >> 62) | (-i5 >>> 62)));
		System.out.println((int) ((i6 >> 62) | (-i6 >>> 62)));
		System.out.println((int) ((i7 >> 62) | (-i7 >>> 62)));
		System.out.println((int) ((i8 >> 62) | (-i8 >>> 62)));
		System.out.println((int) ((i9 >> 62) | (-i9 >>> 62)));
		System.out.println((int) ((i10 >> 62) | (-i10 >>> 62)));
		System.out.println("*******");
		System.out.println((int) ((i0 >> 31) | (-i0 >>> 31)));
		System.out.println((int) ((i1 >> 31) | (-i1 >>> 31)));
		System.out.println((int) ((i2 >> 31) | (-i2 >>> 31)));
		System.out.println((int) ((i3 >> 31) | (-i3 >>> 31)));
		System.out.println((int) ((i4 >> 31) | (-i4 >>> 31)));
		System.out.println((int) ((i5 >> 31) | (-i5 >>> 31)));
		System.out.println((int) ((i6 >> 31) | (-i6 >>> 31)));
		System.out.println((int) ((i7 >> 31) | (-i7 >>> 31)));
		System.out.println((int) ((i8 >> 31) | (-i8 >>> 31)));
		System.out.println((int) ((i9 >> 31) | (-i9 >>> 31)));
		System.out.println((int) ((i10 >> 31) | (-i10 >>> 31)));
		System.out.println("********");
		System.out.println((int) ((i0 >> 32) | (-i0 >>> 32)));
		System.out.println((int) ((i1 >> 32) | (-i1 >>> 32)));
		System.out.println((int) ((i2 >> 32) | (-i2 >>> 32)));
		System.out.println((int) ((i3 >> 32) | (-i3 >>> 32)));
		System.out.println((int) ((i4 >> 32) | (-i4 >>> 32)));
		System.out.println((int) ((i5 >> 32) | (-i5 >>> 32)));
		System.out.println((int) ((i6 >> 32) | (-i6 >>> 32)));
		System.out.println((int) ((i7 >> 32) | (-i7 >>> 32)));
		System.out.println((int) ((i8 >> 32) | (-i8 >>> 32)));
		System.out.println((int) ((i9 >> 32) | (-i9 >>> 32)));
		System.out.println((int) ((i10 >> 32) | (-i10 >>> 32)));
		System.out.println("*********");
		System.out.println((i0 & 0xFFFFFFFFL) << 32 >> 32);
		System.out.println((i1 & 0xFFFFFFFFL) << 32 >> 32);
		System.out.println((i2 & 0xFFFFFFFFL) << 32 >> 32);
		System.out.println((i3 & 0xFFFFFFFFL) << 32 >> 32);
		System.out.println((i4 & 0xFFFFFFFFL) << 32 >> 32);
		System.out.println((i5 & 0xFFFFFFFFL) << 32 >> 32);
		System.out.println((i6 & 0xFFFFFFFFL) << 32 >> 32);
		System.out.println((i7 & 0xFFFFFFFFL) << 32 >> 32);
		System.out.println((i8 & 0xFFFFFFFFL) << 32 >> 32);
		System.out.println((i9 & 0xFFFFFFFFL) << 32 >> 32);
		System.out.println((i10 & 0xFFFFFFFFL) << 32 >> 32);
		
	}
}
